format_version: 4
pipelines:
  deploy_to_uat:
    group: kubernetes
    display_order: 2
    environment_variables:
      NAMESPACE: uat
    secure_variables:
      KUBE_TOKEN: # YOUR VALUE
    materials:
      upstream:
        pipeline: build_and_package
        stage: build_stage
      SourceCodeRepo:
        git: # YOUR VALUE
        shallow_clone: false
    stages:
    - deploy_to_uat:
        approval:
          type: manual
        jobs:
          deploy:
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                command: ./app-deployment.sh
                arguments:
                run_if: passed
    - approval_stage:
        approval: 
          type: manual
        jobs:
          approval_job:
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: echo
                arguments: 
                - "approved"
