format_version: 4
pipelines:
  deploy_to_prod:
    group: kubernetes
    display_order: 3
    environment_variables:
      NAMESPACE: gocd
    secure_variables:
      KUBE_TOKEN: AES:TtHFT0R3dyoH7yViWcu21w==:d9thXuOmFVubEBzrCpIOD4TeKFVBKWvT+TE4FrqoQt844VL+vzSyg0ahbn/gGFrqAKXy7LC0jedcUZ7/XynnNXRHDx6ng0NmvzD4mV4MaWpeNftOBnEbcMNbrvskAskulADDi2DKQVUG1f8jGZpkRcQM0bUzt0WwmUr8w6x/kuAyJ4ah5Met4ma4N20xqIl+32uaSD1LxDFaG7RYcYSbRCEGjaF/YMsp+EampL8gJNHbwqIacuCFGVDQlV3+s/zRd4F+CxWcWcLfUQoMkHXUWLdSpI2GvaiJhNRJd3oKXzTrJbZv6tifplTroJClLZV5efS3nct8nX+Ssju+EFvaWlrSw9FhNl91E2pNxnhxWI1tCKP2pPNZa/9NGBFob1MfIK7J/cQYtFJg5XsVsRQIAnsE/Frd8LYFHibKPlUyYlsXh9plMUkxLIR5on9GakNvYhcjWQlVqZI5deQAn7S3yd910mJIf1N+B5KIVQUiBWFCf0U3DBzDBt/pVFvZyAsInAFj0nfwOMFy1zoDMvUJi8au/5maLDmkLTIJN7BebSs48tnKuZ/QKsiJ3vvic/eyzb4pgUm85sDuR42gaWBwoqWLnkRAf3zpe9nLhAfTqz11Nep/H3NpKhFUaQpmWCLI78ZgL1xRp9CW+zZ5la8gWtKPnlBoPEzsF7ZV9hy5Lg51YkvBwzUdGzcoKtUWwE99UsmNU2c4bNlg0+eTKEqjC7Mc1t54NQL9gX4N4cti9907k6E0hEOGf+0Vsc7K9/dA+RYsIADbaxDiztS8lCNpWccailmU4FzirKLv+6aSUYiJ33ZFxm776pst2xJ2tgtbsO2cQhULNGLuUl71mr3DdTz4tONBDGP9+yorFWJF8QAsE7KH2q+bS/ff0n5p7Cm+bFYuK2LcnFwqTrQHg8+58EZOjdzZsdY33k5vzXwZfZQN1T8qxjAv4cMFcNdJavhtOUZRQpi1q7++1qYn7pDF0odo8rrmGTfaboyH1fyDsb0PoLpYPpR3lzHcpJymDhDp3EWzkeIZU+cnRAmgjghhwpTaHg86OuvNY8+hguFgF19LDMAMJ9CvpEjyt+dsVGXeTYuo1y3fNl4a7zPylbe66Q==
    materials:
      compliance_material:
        pipeline: compliance
        stage: compliance_stage
      uat:
        pipeline: deploy_to_uat
        stage: approval_stage
      SourceCodeRepo:
        git: https://github.com/kmugrage/node-bulletin-board
        shallow_clone: false
    stages:
    - deploy_to_prod:
        approval:
          type: success
        jobs:
          deploy:
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                options:
                  EnvironmentVariablePrefix: ''
                  SkipImagePulling: 'true'
                artifact_id: bulletin-board
                pipeline: build_and_package/deploy_to_uat
                stage: build_stage
                job: build_image
                artifact_origin: external
                run_if: passed
            - exec:
                command: ./app-deployment.sh
                arguments:
                run_if: passed
